// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVhuHiKwIL7o_AwgiazzOFrthxWTPF6fM',
    appId: '1:256643882377:web:ddc92a8508168900e91558',
    messagingSenderId: '256643882377',
    projectId: 'flutter-78b20',
    authDomain: 'flutter-78b20.firebaseapp.com',
    databaseURL: 'https://flutter-78b20-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-78b20.appspot.com',
    measurementId: 'G-Z1Z5BLVNX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFLPAbvCZf1YR7qSdwP9VatGnsO68_9Ks',
    appId: '1:256643882377:android:b0fbe0b44041a471e91558',
    messagingSenderId: '256643882377',
    projectId: 'flutter-78b20',
    databaseURL: 'https://flutter-78b20-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-78b20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv6ODgUlYdgX-U3rlIgrnZd8_5Qu7rWF8',
    appId: '1:256643882377:ios:9ea834debaa88a9fe91558',
    messagingSenderId: '256643882377',
    projectId: 'flutter-78b20',
    databaseURL: 'https://flutter-78b20-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-78b20.appspot.com',
    iosClientId: '256643882377-kh2dv4kknk12ud7oq82fbqnn3o6g4orl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv6ODgUlYdgX-U3rlIgrnZd8_5Qu7rWF8',
    appId: '1:256643882377:ios:38f69fc3c0d0f210e91558',
    messagingSenderId: '256643882377',
    projectId: 'flutter-78b20',
    databaseURL: 'https://flutter-78b20-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-78b20.appspot.com',
    iosClientId: '256643882377-ibam5gl8vo13toj70sskve118debc8gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
